/*==============================================================
  SCRIPT 01 - CREACIÓN DE BASE DE DATOS Y TABLAS
  PROYECTO : MASKOTEKA - GESTIÓN DE CITAS VETERINARIAS
  MOTOR    : Microsoft SQL Server
==============================================================*/

USE master;
GO

IF DB_ID('BD_MASKOTEKA') IS NULL
BEGIN
    CREATE DATABASE BD_MASKOTEKA;
END;
GO

USE BD_MASKOTEKA;
GO

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

/*==============================================================
  1. ELIMINACIÓN CONTROLADA PARA REEJECUTAR EL SCRIPT
==============================================================*/
DROP TABLE IF EXISTS dbo.TB_DOCUMENTO_MASCOTA;
DROP TABLE IF EXISTS dbo.TB_VACUNA_MASCOTA;
DROP TABLE IF EXISTS dbo.TB_CONSULTA_MASCOTA;
DROP TABLE IF EXISTS dbo.TB_PAGO;
DROP TABLE IF EXISTS dbo.TB_CITA_ESTADO_HISTORIAL;
DROP TABLE IF EXISTS dbo.TB_CITA;
DROP TABLE IF EXISTS dbo.TB_DISPONIBILIDAD;
DROP TABLE IF EXISTS dbo.TM_SERVICIO;
DROP TABLE IF EXISTS dbo.TM_VETERINARIO;
DROP TABLE IF EXISTS dbo.TM_MASCOTA;
DROP TABLE IF EXISTS dbo.TM_ESPECIE;
DROP TABLE IF EXISTS dbo.TM_USUARIO;
DROP TABLE IF EXISTS dbo.TM_ROL;
GO

/*==============================================================
  2. TABLAS MAESTRAS
==============================================================*/
CREATE TABLE dbo.TM_ROL
(
    ID_ROL          INT IDENTITY(1,1) NOT NULL,
    NOMBRE          VARCHAR(30) NOT NULL,
    DESCRIPCION     VARCHAR(150) NULL,
    ACTIVO          BIT NOT NULL CONSTRAINT DF_TM_ROL_ACTIVO DEFAULT (1),
    FECHA_CREACION  DATETIME2(0) NOT NULL CONSTRAINT DF_TM_ROL_FECHA DEFAULT (SYSDATETIME()),
    CONSTRAINT PK_TM_ROL PRIMARY KEY (ID_ROL),
    CONSTRAINT UQ_TM_ROL_NOMBRE UNIQUE (NOMBRE)
);
GO

CREATE TABLE dbo.TM_USUARIO
(
    ID_USUARIO          INT IDENTITY(1,1) NOT NULL,
    ID_ROL              INT NOT NULL,
    NOMBRES             VARCHAR(80) NOT NULL,
    APELLIDOS           VARCHAR(100) NOT NULL,
    TIPO_DOCUMENTO      VARCHAR(10) NULL,
    NUMERO_DOCUMENTO    VARCHAR(15) NULL,
    TELEFONO            VARCHAR(20) NULL,
    CORREO              VARCHAR(120) NOT NULL,
    CLAVE               VARCHAR(255) NOT NULL,
    DIRECCION           VARCHAR(200) NULL,
    ACTIVO              BIT NOT NULL CONSTRAINT DF_TM_USUARIO_ACTIVO DEFAULT (1),
    FECHA_CREACION      DATETIME2(0) NOT NULL CONSTRAINT DF_TM_USUARIO_FECHA DEFAULT (SYSDATETIME()),
    FECHA_MODIFICACION  DATETIME2(0) NULL,
    CONSTRAINT PK_TM_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_TM_USUARIO_ROL FOREIGN KEY (ID_ROL) REFERENCES dbo.TM_ROL(ID_ROL),
    CONSTRAINT UQ_TM_USUARIO_CORREO UNIQUE (CORREO),
    CONSTRAINT CK_TM_USUARIO_CORREO CHECK (CORREO LIKE '%_@_%._%')
);
GO

CREATE TABLE dbo.TM_ESPECIE
(
    ID_ESPECIE      INT IDENTITY(1,1) NOT NULL,
    NOMBRE          VARCHAR(50) NOT NULL,
    ACTIVO          BIT NOT NULL CONSTRAINT DF_TM_ESPECIE_ACTIVO DEFAULT (1),
    CONSTRAINT PK_TM_ESPECIE PRIMARY KEY (ID_ESPECIE),
    CONSTRAINT UQ_TM_ESPECIE_NOMBRE UNIQUE (NOMBRE)
);
GO

CREATE TABLE dbo.TM_MASCOTA
(
    ID_MASCOTA          INT IDENTITY(1,1) NOT NULL,
    ID_USUARIO          INT NOT NULL,
    ID_ESPECIE          INT NOT NULL,
    NOMBRE              VARCHAR(60) NOT NULL,
    RAZA                VARCHAR(80) NULL,
    SEXO                CHAR(1) NOT NULL,
    FECHA_NACIMIENTO    DATE NULL,
    PESO_KG             DECIMAL(6,2) NULL,
    COLOR               VARCHAR(80) NULL,
    ESTERILIZADO        BIT NOT NULL CONSTRAINT DF_TM_MASCOTA_ESTERILIZADO DEFAULT (0),
    MICROCHIP           VARCHAR(30) NULL,
    FOTO_URL            VARCHAR(300) NULL,
    OBSERVACIONES       VARCHAR(500) NULL,
    ACTIVO              BIT NOT NULL CONSTRAINT DF_TM_MASCOTA_ACTIVO DEFAULT (1),
    FECHA_CREACION      DATETIME2(0) NOT NULL CONSTRAINT DF_TM_MASCOTA_FECHA DEFAULT (SYSDATETIME()),
    FECHA_MODIFICACION  DATETIME2(0) NULL,
    CONSTRAINT PK_TM_MASCOTA PRIMARY KEY (ID_MASCOTA),
    CONSTRAINT FK_TM_MASCOTA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES dbo.TM_USUARIO(ID_USUARIO),
    CONSTRAINT FK_TM_MASCOTA_ESPECIE FOREIGN KEY (ID_ESPECIE) REFERENCES dbo.TM_ESPECIE(ID_ESPECIE),
    CONSTRAINT CK_TM_MASCOTA_SEXO CHECK (SEXO IN ('M','H')),
    CONSTRAINT CK_TM_MASCOTA_PESO CHECK (PESO_KG IS NULL OR PESO_KG > 0)
);
GO

/* SQL Server solo permite un NULL en una restricción UNIQUE tradicional.
   Este índice exige unicidad únicamente cuando el microchip tiene valor. */
CREATE UNIQUE INDEX UX_TM_MASCOTA_MICROCHIP
    ON dbo.TM_MASCOTA (MICROCHIP)
    WHERE MICROCHIP IS NOT NULL;
GO

CREATE TABLE dbo.TM_VETERINARIO
(
    ID_VETERINARIO      INT IDENTITY(1,1) NOT NULL,
    NOMBRES             VARCHAR(80) NOT NULL,
    APELLIDOS           VARCHAR(100) NOT NULL,
    CMPV                VARCHAR(20) NOT NULL,
    ESPECIALIDAD        VARCHAR(100) NULL,
    TELEFONO            VARCHAR(20) NULL,
    CORREO              VARCHAR(120) NULL,
    ACTIVO              BIT NOT NULL CONSTRAINT DF_TM_VETERINARIO_ACTIVO DEFAULT (1),
    CONSTRAINT PK_TM_VETERINARIO PRIMARY KEY (ID_VETERINARIO),
    CONSTRAINT UQ_TM_VETERINARIO_CMPV UNIQUE (CMPV)
);
GO

CREATE TABLE dbo.TM_SERVICIO
(
    ID_SERVICIO         INT IDENTITY(1,1) NOT NULL,
    NOMBRE              VARCHAR(100) NOT NULL,
    DESCRIPCION         VARCHAR(300) NULL,
    DURACION_MINUTOS    SMALLINT NOT NULL,
    PRECIO              DECIMAL(10,2) NOT NULL,
    ACTIVO              BIT NOT NULL CONSTRAINT DF_TM_SERVICIO_ACTIVO DEFAULT (1),
    CONSTRAINT PK_TM_SERVICIO PRIMARY KEY (ID_SERVICIO),
    CONSTRAINT UQ_TM_SERVICIO_NOMBRE UNIQUE (NOMBRE),
    CONSTRAINT CK_TM_SERVICIO_DURACION CHECK (DURACION_MINUTOS BETWEEN 10 AND 480),
    CONSTRAINT CK_TM_SERVICIO_PRECIO CHECK (PRECIO >= 0)
);
GO

/*==============================================================
  3. TABLAS TRANSACCIONALES
==============================================================*/
CREATE TABLE dbo.TB_DISPONIBILIDAD
(
    ID_DISPONIBILIDAD   INT IDENTITY(1,1) NOT NULL,
    ID_VETERINARIO      INT NOT NULL,
    FECHA_ATENCION      DATE NOT NULL,
    HORA_INICIO         TIME(0) NOT NULL,
    HORA_FIN            TIME(0) NOT NULL,
    ESTADO              VARCHAR(15) NOT NULL CONSTRAINT DF_TB_DISP_ESTADO DEFAULT ('DISPONIBLE'),
    FECHA_CREACION      DATETIME2(0) NOT NULL CONSTRAINT DF_TB_DISP_FECHA DEFAULT (SYSDATETIME()),
    CONSTRAINT PK_TB_DISPONIBILIDAD PRIMARY KEY (ID_DISPONIBILIDAD),
    CONSTRAINT FK_TB_DISP_VETERINARIO FOREIGN KEY (ID_VETERINARIO) REFERENCES dbo.TM_VETERINARIO(ID_VETERINARIO),
    CONSTRAINT CK_TB_DISP_HORAS CHECK (HORA_FIN > HORA_INICIO),
    CONSTRAINT CK_TB_DISP_ESTADO CHECK (ESTADO IN ('DISPONIBLE','RESERVADO','BLOQUEADO')),
    CONSTRAINT UQ_TB_DISP_SLOT UNIQUE (ID_VETERINARIO, FECHA_ATENCION, HORA_INICIO)
);
GO

CREATE TABLE dbo.TB_CITA
(
    ID_CITA              INT IDENTITY(1,1) NOT NULL,
    ID_MASCOTA           INT NOT NULL,
    ID_SERVICIO          INT NOT NULL,
    ID_VETERINARIO       INT NOT NULL,
    ID_DISPONIBILIDAD    INT NOT NULL,
    MOTIVO_CONSULTA      VARCHAR(500) NULL,
    ESTADO               VARCHAR(15) NOT NULL CONSTRAINT DF_TB_CITA_ESTADO DEFAULT ('PENDIENTE'),
    PRECIO_RESERVADO     DECIMAL(10,2) NOT NULL,
    OBSERVACIONES        VARCHAR(500) NULL,
    FECHA_CREACION       DATETIME2(0) NOT NULL CONSTRAINT DF_TB_CITA_FECHA DEFAULT (SYSDATETIME()),
    FECHA_MODIFICACION   DATETIME2(0) NULL,
    CONSTRAINT PK_TB_CITA PRIMARY KEY (ID_CITA),
    CONSTRAINT FK_TB_CITA_MASCOTA FOREIGN KEY (ID_MASCOTA) REFERENCES dbo.TM_MASCOTA(ID_MASCOTA),
    CONSTRAINT FK_TB_CITA_SERVICIO FOREIGN KEY (ID_SERVICIO) REFERENCES dbo.TM_SERVICIO(ID_SERVICIO),
    CONSTRAINT FK_TB_CITA_VETERINARIO FOREIGN KEY (ID_VETERINARIO) REFERENCES dbo.TM_VETERINARIO(ID_VETERINARIO),
    CONSTRAINT FK_TB_CITA_DISPONIBILIDAD FOREIGN KEY (ID_DISPONIBILIDAD) REFERENCES dbo.TB_DISPONIBILIDAD(ID_DISPONIBILIDAD),
    CONSTRAINT UQ_TB_CITA_DISPONIBILIDAD UNIQUE (ID_DISPONIBILIDAD),
    CONSTRAINT CK_TB_CITA_ESTADO CHECK (ESTADO IN ('PENDIENTE','CONFIRMADA','COMPLETADA','CANCELADA','NO_ASISTIO')),
    CONSTRAINT CK_TB_CITA_PRECIO CHECK (PRECIO_RESERVADO >= 0)
);
GO

CREATE TABLE dbo.TB_CITA_ESTADO_HISTORIAL
(
    ID_HISTORIAL        BIGINT IDENTITY(1,1) NOT NULL,
    ID_CITA             INT NOT NULL,
    ESTADO_ANTERIOR     VARCHAR(15) NULL,
    ESTADO_NUEVO        VARCHAR(15) NOT NULL,
    MOTIVO              VARCHAR(300) NULL,
    ID_USUARIO_ACCION   INT NULL,
    FECHA_CAMBIO        DATETIME2(0) NOT NULL CONSTRAINT DF_TB_HIST_FECHA DEFAULT (SYSDATETIME()),
    CONSTRAINT PK_TB_CITA_ESTADO_HIST PRIMARY KEY (ID_HISTORIAL),
    CONSTRAINT FK_TB_HIST_CITA FOREIGN KEY (ID_CITA) REFERENCES dbo.TB_CITA(ID_CITA),
    CONSTRAINT FK_TB_HIST_USUARIO FOREIGN KEY (ID_USUARIO_ACCION) REFERENCES dbo.TM_USUARIO(ID_USUARIO)
);
GO

CREATE TABLE dbo.TB_PAGO
(
    ID_PAGO              INT IDENTITY(1,1) NOT NULL,
    ID_CITA              INT NOT NULL,
    MONTO                DECIMAL(10,2) NOT NULL,
    METODO               VARCHAR(20) NOT NULL,
    ESTADO               VARCHAR(15) NOT NULL CONSTRAINT DF_TB_PAGO_ESTADO DEFAULT ('PENDIENTE'),
    CODIGO_TRANSACCION   VARCHAR(80) NULL,
    ULTIMOS_4            CHAR(4) NULL,
    FECHA_PAGO           DATETIME2(0) NULL,
    FECHA_CREACION       DATETIME2(0) NOT NULL CONSTRAINT DF_TB_PAGO_FECHA DEFAULT (SYSDATETIME()),
    CONSTRAINT PK_TB_PAGO PRIMARY KEY (ID_PAGO),
    CONSTRAINT FK_TB_PAGO_CITA FOREIGN KEY (ID_CITA) REFERENCES dbo.TB_CITA(ID_CITA),
    CONSTRAINT CK_TB_PAGO_MONTO CHECK (MONTO >= 0),
    CONSTRAINT CK_TB_PAGO_METODO CHECK (METODO IN ('TARJETA','EFECTIVO','YAPE','PLIN')),
    CONSTRAINT CK_TB_PAGO_ESTADO CHECK (ESTADO IN ('PENDIENTE','APROBADO','RECHAZADO','REEMBOLSADO')),
    CONSTRAINT CK_TB_PAGO_ULTIMOS4 CHECK (ULTIMOS_4 IS NULL OR ULTIMOS_4 NOT LIKE '%[^0-9]%')
);
GO

/* Índices de consulta frecuente */
CREATE INDEX IX_TM_MASCOTA_USUARIO ON dbo.TM_MASCOTA(ID_USUARIO, ACTIVO);
CREATE INDEX IX_TB_DISP_FECHA_ESTADO ON dbo.TB_DISPONIBILIDAD(FECHA_ATENCION, ESTADO);
CREATE INDEX IX_TB_CITA_MASCOTA ON dbo.TB_CITA(ID_MASCOTA, ESTADO);
CREATE INDEX IX_TB_CITA_VETERINARIO ON dbo.TB_CITA(ID_VETERINARIO, ESTADO);
CREATE INDEX IX_TB_PAGO_CITA ON dbo.TB_PAGO(ID_CITA, ESTADO);
GO

/*==============================================================
  4. TABLAS COMPLEMENTARIAS DEL FRONTEND
==============================================================*/
IF OBJECT_ID('dbo.TB_DOCUMENTO_MASCOTA','U') IS NULL
CREATE TABLE dbo.TB_DOCUMENTO_MASCOTA(
 ID_DOCUMENTO INT IDENTITY PRIMARY KEY, ID_MASCOTA INT NOT NULL,
 NOMBRE VARCHAR(150) NOT NULL, TIPO VARCHAR(50) NOT NULL, URL VARCHAR(500) NOT NULL,
 DESCRIPCION VARCHAR(300) NULL, FECHA_CREACION DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
 CONSTRAINT FK_DOCUMENTO_MASCOTA FOREIGN KEY(ID_MASCOTA) REFERENCES dbo.TM_MASCOTA(ID_MASCOTA));
GO
IF OBJECT_ID('dbo.TB_VACUNA_MASCOTA','U') IS NULL
CREATE TABLE dbo.TB_VACUNA_MASCOTA(
 ID_VACUNA INT IDENTITY PRIMARY KEY, ID_MASCOTA INT NOT NULL, ID_VETERINARIO INT NULL,
 NOMBRE_VACUNA VARCHAR(120) NOT NULL, FECHA_APLICACION DATE NOT NULL, FECHA_PROXIMA DATE NULL,
 OBSERVACIONES VARCHAR(300) NULL, FECHA_CREACION DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
 CONSTRAINT FK_VACUNA_MASCOTA FOREIGN KEY(ID_MASCOTA) REFERENCES dbo.TM_MASCOTA(ID_MASCOTA),
 CONSTRAINT FK_VACUNA_VETERINARIO FOREIGN KEY(ID_VETERINARIO) REFERENCES dbo.TM_VETERINARIO(ID_VETERINARIO));
GO
IF OBJECT_ID('dbo.TB_CONSULTA_MASCOTA','U') IS NULL
CREATE TABLE dbo.TB_CONSULTA_MASCOTA(
 ID_CONSULTA INT IDENTITY PRIMARY KEY, ID_MASCOTA INT NOT NULL, ID_VETERINARIO INT NULL,
 FECHA_CONSULTA DATETIME2(0) NOT NULL, DIAGNOSTICO VARCHAR(500) NOT NULL,
 TRATAMIENTO VARCHAR(500) NULL, PESO_KG DECIMAL(6,2) NULL,
 FECHA_CREACION DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
 CONSTRAINT FK_CONSULTA_MASCOTA FOREIGN KEY(ID_MASCOTA) REFERENCES dbo.TM_MASCOTA(ID_MASCOTA),
 CONSTRAINT FK_CONSULTA_VETERINARIO FOREIGN KEY(ID_VETERINARIO) REFERENCES dbo.TM_VETERINARIO(ID_VETERINARIO));
GO
