/*==============================================================
  SCRIPT 02 - PROCEDIMIENTOS ALMACENADOS
  PROYECTO : MASKOTEKA - GESTIÓN DE CITAS VETERINARIAS
  MOTOR    : Microsoft SQL Server
==============================================================*/

USE BD_MASKOTEKA;
GO

IF DB_NAME() <> 'BD_MASKOTEKA'

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

/*==============================================================
  4. PROCEDIMIENTOS ALMACENADOS
==============================================================*/
IF OBJECT_ID('dbo.usp_Usuario_Registrar', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Usuario_Registrar;
GO

CREATE PROCEDURE dbo.usp_Usuario_Registrar
    @NOMBRES            VARCHAR(80),
    @APELLIDOS          VARCHAR(100),
    @CORREO             VARCHAR(120),
    @CLAVE              VARCHAR(255),
    @TELEFONO           VARCHAR(20) = NULL,
    @TIPO_DOCUMENTO     VARCHAR(10) = NULL,
    @NUMERO_DOCUMENTO   VARCHAR(15) = NULL,
    @DIRECCION          VARCHAR(200) = NULL,
    @ID_USUARIO         INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM dbo.TM_USUARIO WHERE CORREO = LOWER(LTRIM(RTRIM(@CORREO))))
        THROW 50001, 'El correo ya se encuentra registrado.', 1;

    DECLARE @ID_ROL_CLIENTE INT = (SELECT ID_ROL FROM dbo.TM_ROL WHERE NOMBRE = 'CLIENTE');

    INSERT INTO dbo.TM_USUARIO
        (ID_ROL, NOMBRES, APELLIDOS, TIPO_DOCUMENTO, NUMERO_DOCUMENTO,
         TELEFONO, CORREO, CLAVE, DIRECCION)
    VALUES
        (@ID_ROL_CLIENTE, LTRIM(RTRIM(@NOMBRES)), LTRIM(RTRIM(@APELLIDOS)),
         @TIPO_DOCUMENTO, @NUMERO_DOCUMENTO, @TELEFONO,
         LOWER(LTRIM(RTRIM(@CORREO))), @CLAVE, @DIRECCION);

    SET @ID_USUARIO = CONVERT(INT, SCOPE_IDENTITY());
END;
GO

IF OBJECT_ID('dbo.usp_Usuario_Login', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Usuario_Login;
GO

CREATE PROCEDURE dbo.usp_Usuario_Login
    @CORREO VARCHAR(120)
AS
BEGIN
    SET NOCOUNT ON;
    /* La comparación del hash debe realizarse en el backend. */
    SELECT U.ID_USUARIO, U.NOMBRES, U.APELLIDOS, U.CORREO, U.CLAVE,
           R.NOMBRE AS ROL
    FROM dbo.TM_USUARIO U
    INNER JOIN dbo.TM_ROL R ON R.ID_ROL = U.ID_ROL
    WHERE U.CORREO = LOWER(LTRIM(RTRIM(@CORREO)))
      AND U.ACTIVO = 1;
END;
GO

IF OBJECT_ID('dbo.usp_Usuario_ObtenerPerfil', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Usuario_ObtenerPerfil;
GO

CREATE PROCEDURE dbo.usp_Usuario_ObtenerPerfil
    @ID_USUARIO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT U.ID_USUARIO, U.NOMBRES, U.APELLIDOS, U.TIPO_DOCUMENTO,
           U.NUMERO_DOCUMENTO, U.TELEFONO, U.CORREO, U.DIRECCION,
           R.NOMBRE AS ROL, U.FECHA_CREACION
    FROM dbo.TM_USUARIO U
    INNER JOIN dbo.TM_ROL R ON R.ID_ROL = U.ID_ROL
    WHERE U.ID_USUARIO = @ID_USUARIO AND U.ACTIVO = 1;
END;
GO

IF OBJECT_ID('dbo.usp_Mascota_ListarPorUsuario', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Mascota_ListarPorUsuario;
GO

CREATE PROCEDURE dbo.usp_Mascota_ListarPorUsuario
    @ID_USUARIO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT M.ID_MASCOTA, M.NOMBRE, E.NOMBRE AS ESPECIE, M.RAZA, M.SEXO,
           M.FECHA_NACIMIENTO, M.PESO_KG, M.COLOR, M.ESTERILIZADO,
           M.MICROCHIP, M.FOTO_URL, M.OBSERVACIONES
    FROM dbo.TM_MASCOTA M
    INNER JOIN dbo.TM_ESPECIE E ON E.ID_ESPECIE = M.ID_ESPECIE
    WHERE M.ID_USUARIO = @ID_USUARIO AND M.ACTIVO = 1
    ORDER BY M.NOMBRE;
END;
GO

IF OBJECT_ID('dbo.usp_Mascota_Registrar', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Mascota_Registrar;
GO

CREATE PROCEDURE dbo.usp_Mascota_Registrar
    @ID_USUARIO         INT,
    @ID_ESPECIE         INT,
    @NOMBRE             VARCHAR(60),
    @RAZA               VARCHAR(80) = NULL,
    @SEXO               CHAR(1),
    @FECHA_NACIMIENTO   DATE = NULL,
    @PESO_KG            DECIMAL(6,2) = NULL,
    @COLOR              VARCHAR(80) = NULL,
    @ESTERILIZADO       BIT = 0,
    @MICROCHIP          VARCHAR(30) = NULL,
    @FOTO_URL           VARCHAR(300) = NULL,
    @OBSERVACIONES      VARCHAR(500) = NULL,
    @ID_MASCOTA         INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM dbo.TM_USUARIO WHERE ID_USUARIO = @ID_USUARIO AND ACTIVO = 1)
        THROW 50002, 'El usuario no existe o está inactivo.', 1;

    INSERT INTO dbo.TM_MASCOTA
        (ID_USUARIO, ID_ESPECIE, NOMBRE, RAZA, SEXO, FECHA_NACIMIENTO,
         PESO_KG, COLOR, ESTERILIZADO, MICROCHIP, FOTO_URL, OBSERVACIONES)
    VALUES
        (@ID_USUARIO, @ID_ESPECIE, LTRIM(RTRIM(@NOMBRE)), @RAZA, @SEXO,
         @FECHA_NACIMIENTO, @PESO_KG, @COLOR, @ESTERILIZADO,
         NULLIF(LTRIM(RTRIM(@MICROCHIP)), ''), @FOTO_URL, @OBSERVACIONES);

    SET @ID_MASCOTA = CONVERT(INT, SCOPE_IDENTITY());
END;
GO

IF OBJECT_ID('dbo.usp_Mascota_Actualizar', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Mascota_Actualizar;
GO

CREATE PROCEDURE dbo.usp_Mascota_Actualizar
    @ID_MASCOTA         INT,
    @ID_USUARIO         INT,
    @ID_ESPECIE         INT,
    @NOMBRE             VARCHAR(60),
    @RAZA               VARCHAR(80) = NULL,
    @SEXO               CHAR(1),
    @FECHA_NACIMIENTO   DATE = NULL,
    @PESO_KG            DECIMAL(6,2) = NULL,
    @COLOR              VARCHAR(80) = NULL,
    @ESTERILIZADO       BIT = 0,
    @MICROCHIP          VARCHAR(30) = NULL,
    @FOTO_URL           VARCHAR(300) = NULL,
    @OBSERVACIONES      VARCHAR(500) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE dbo.TM_MASCOTA
       SET ID_ESPECIE = @ID_ESPECIE,
           NOMBRE = LTRIM(RTRIM(@NOMBRE)),
           RAZA = @RAZA,
           SEXO = @SEXO,
           FECHA_NACIMIENTO = @FECHA_NACIMIENTO,
           PESO_KG = @PESO_KG,
           COLOR = @COLOR,
           ESTERILIZADO = @ESTERILIZADO,
           MICROCHIP = NULLIF(LTRIM(RTRIM(@MICROCHIP)), ''),
           FOTO_URL = @FOTO_URL,
           OBSERVACIONES = @OBSERVACIONES,
           FECHA_MODIFICACION = SYSDATETIME()
     WHERE ID_MASCOTA = @ID_MASCOTA
       AND ID_USUARIO = @ID_USUARIO
       AND ACTIVO = 1;

    IF @@ROWCOUNT = 0
        THROW 50003, 'No se encontró la mascota para el usuario indicado.', 1;
END;
GO

IF OBJECT_ID('dbo.usp_Mascota_Eliminar', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Mascota_Eliminar;
GO

CREATE PROCEDURE dbo.usp_Mascota_Eliminar
    @ID_MASCOTA INT,
    @ID_USUARIO INT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS
    (
        SELECT 1 FROM dbo.TB_CITA
        WHERE ID_MASCOTA = @ID_MASCOTA
          AND ESTADO IN ('PENDIENTE','CONFIRMADA')
    )
        THROW 50004, 'No se puede eliminar una mascota con citas pendientes o confirmadas.', 1;

    UPDATE dbo.TM_MASCOTA
       SET ACTIVO = 0,
           FECHA_MODIFICACION = SYSDATETIME()
     WHERE ID_MASCOTA = @ID_MASCOTA
       AND ID_USUARIO = @ID_USUARIO;
END;
GO

IF OBJECT_ID('dbo.usp_Servicio_Listar', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Servicio_Listar;
GO

CREATE PROCEDURE dbo.usp_Servicio_Listar
AS
BEGIN
    SET NOCOUNT ON;
    SELECT ID_SERVICIO, NOMBRE, DESCRIPCION, DURACION_MINUTOS, PRECIO
    FROM dbo.TM_SERVICIO
    WHERE ACTIVO = 1
    ORDER BY NOMBRE;
END;
GO

IF OBJECT_ID('dbo.usp_Disponibilidad_Listar', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Disponibilidad_Listar;
GO

CREATE PROCEDURE dbo.usp_Disponibilidad_Listar
    @FECHA_DESDE       DATE,
    @FECHA_HASTA       DATE,
    @ID_VETERINARIO   INT = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT D.ID_DISPONIBILIDAD, D.FECHA_ATENCION, D.HORA_INICIO, D.HORA_FIN,
           V.ID_VETERINARIO,
           CONCAT(V.NOMBRES, ' ', V.APELLIDOS) AS VETERINARIO,
           V.ESPECIALIDAD
    FROM dbo.TB_DISPONIBILIDAD D
    INNER JOIN dbo.TM_VETERINARIO V ON V.ID_VETERINARIO = D.ID_VETERINARIO
    WHERE D.FECHA_ATENCION BETWEEN @FECHA_DESDE AND @FECHA_HASTA
      AND D.ESTADO = 'DISPONIBLE'
      AND V.ACTIVO = 1
      AND (@ID_VETERINARIO IS NULL OR D.ID_VETERINARIO = @ID_VETERINARIO)
    ORDER BY D.FECHA_ATENCION, D.HORA_INICIO;
END;
GO

IF OBJECT_ID('dbo.usp_Cita_ListarPorUsuario', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Cita_ListarPorUsuario;
GO

CREATE PROCEDURE dbo.usp_Cita_ListarPorUsuario
    @ID_USUARIO INT,
    @ESTADO     VARCHAR(15) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT C.ID_CITA, M.ID_MASCOTA, M.NOMBRE AS MASCOTA,
           S.NOMBRE AS SERVICIO, C.PRECIO_RESERVADO,
           D.FECHA_ATENCION, D.HORA_INICIO, D.HORA_FIN,
           CONCAT(V.NOMBRES, ' ', V.APELLIDOS) AS VETERINARIO,
           C.ESTADO, C.MOTIVO_CONSULTA, C.FECHA_CREACION
    FROM dbo.TB_CITA C
    INNER JOIN dbo.TM_MASCOTA M ON M.ID_MASCOTA = C.ID_MASCOTA
    INNER JOIN dbo.TM_SERVICIO S ON S.ID_SERVICIO = C.ID_SERVICIO
    INNER JOIN dbo.TB_DISPONIBILIDAD D ON D.ID_DISPONIBILIDAD = C.ID_DISPONIBILIDAD
    INNER JOIN dbo.TM_VETERINARIO V ON V.ID_VETERINARIO = C.ID_VETERINARIO
    WHERE M.ID_USUARIO = @ID_USUARIO
      AND (@ESTADO IS NULL OR C.ESTADO = @ESTADO)
    ORDER BY D.FECHA_ATENCION DESC, D.HORA_INICIO DESC;
END;
GO

IF OBJECT_ID('dbo.usp_Cita_Registrar', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Cita_Registrar;
GO

CREATE PROCEDURE dbo.usp_Cita_Registrar
    @ID_USUARIO         INT,
    @ID_MASCOTA         INT,
    @ID_SERVICIO        INT,
    @ID_DISPONIBILIDAD  INT,
    @MOTIVO_CONSULTA    VARCHAR(500) = NULL,
    @ID_CITA            INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    BEGIN TRY
        BEGIN TRANSACTION;

        IF NOT EXISTS
        (
            SELECT 1 FROM dbo.TM_MASCOTA
            WHERE ID_MASCOTA = @ID_MASCOTA
              AND ID_USUARIO = @ID_USUARIO
              AND ACTIVO = 1
        )
            THROW 50005, 'La mascota no pertenece al usuario indicado.', 1;

        DECLARE @ID_VETERINARIO INT;

        SELECT @ID_VETERINARIO = ID_VETERINARIO
        FROM dbo.TB_DISPONIBILIDAD WITH (UPDLOCK, HOLDLOCK)
        WHERE ID_DISPONIBILIDAD = @ID_DISPONIBILIDAD
          AND ESTADO = 'DISPONIBLE';

        IF @ID_VETERINARIO IS NULL
            THROW 50006, 'El horario ya no se encuentra disponible.', 1;

        DECLARE @PRECIO DECIMAL(10,2) =
        (
            SELECT PRECIO FROM dbo.TM_SERVICIO
            WHERE ID_SERVICIO = @ID_SERVICIO AND ACTIVO = 1
        );

        IF @PRECIO IS NULL
            THROW 50007, 'El servicio no existe o está inactivo.', 1;

        INSERT INTO dbo.TB_CITA
            (ID_MASCOTA, ID_SERVICIO, ID_VETERINARIO, ID_DISPONIBILIDAD,
             MOTIVO_CONSULTA, ESTADO, PRECIO_RESERVADO)
        VALUES
            (@ID_MASCOTA, @ID_SERVICIO, @ID_VETERINARIO, @ID_DISPONIBILIDAD,
             @MOTIVO_CONSULTA, 'PENDIENTE', @PRECIO);

        SET @ID_CITA = CONVERT(INT, SCOPE_IDENTITY());

        UPDATE dbo.TB_DISPONIBILIDAD
           SET ESTADO = 'RESERVADO'
         WHERE ID_DISPONIBILIDAD = @ID_DISPONIBILIDAD;

        INSERT INTO dbo.TB_CITA_ESTADO_HISTORIAL
            (ID_CITA, ESTADO_ANTERIOR, ESTADO_NUEVO, MOTIVO, ID_USUARIO_ACCION)
        VALUES
            (@ID_CITA, NULL, 'PENDIENTE', 'Registro inicial de la cita', @ID_USUARIO);

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

IF OBJECT_ID('dbo.usp_Cita_Reprogramar', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Cita_Reprogramar;
GO

CREATE PROCEDURE dbo.usp_Cita_Reprogramar
    @ID_CITA                    INT,
    @ID_USUARIO                 INT,
    @ID_NUEVA_DISPONIBILIDAD    INT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    BEGIN TRY
        BEGIN TRANSACTION;

        DECLARE @ID_DISP_ANTERIOR INT;

        SELECT @ID_DISP_ANTERIOR = C.ID_DISPONIBILIDAD
        FROM dbo.TB_CITA C
        INNER JOIN dbo.TM_MASCOTA M ON M.ID_MASCOTA = C.ID_MASCOTA
        WHERE C.ID_CITA = @ID_CITA
          AND M.ID_USUARIO = @ID_USUARIO
          AND C.ESTADO IN ('PENDIENTE','CONFIRMADA');

        IF @ID_DISP_ANTERIOR IS NULL
            THROW 50008, 'La cita no existe, no pertenece al usuario o no puede reprogramarse.', 1;

        DECLARE @ID_NUEVO_VETERINARIO INT;

        SELECT @ID_NUEVO_VETERINARIO = ID_VETERINARIO
        FROM dbo.TB_DISPONIBILIDAD WITH (UPDLOCK, HOLDLOCK)
        WHERE ID_DISPONIBILIDAD = @ID_NUEVA_DISPONIBILIDAD
          AND ESTADO = 'DISPONIBLE';

        IF @ID_NUEVO_VETERINARIO IS NULL
            THROW 50009, 'El nuevo horario ya no está disponible.', 1;

        UPDATE dbo.TB_DISPONIBILIDAD SET ESTADO = 'DISPONIBLE'
        WHERE ID_DISPONIBILIDAD = @ID_DISP_ANTERIOR;

        UPDATE dbo.TB_DISPONIBILIDAD SET ESTADO = 'RESERVADO'
        WHERE ID_DISPONIBILIDAD = @ID_NUEVA_DISPONIBILIDAD;

        UPDATE dbo.TB_CITA
           SET ID_DISPONIBILIDAD = @ID_NUEVA_DISPONIBILIDAD,
               ID_VETERINARIO = @ID_NUEVO_VETERINARIO,
               FECHA_MODIFICACION = SYSDATETIME()
         WHERE ID_CITA = @ID_CITA;

        INSERT INTO dbo.TB_CITA_ESTADO_HISTORIAL
            (ID_CITA, ESTADO_ANTERIOR, ESTADO_NUEVO, MOTIVO, ID_USUARIO_ACCION)
        SELECT ID_CITA, ESTADO, ESTADO, 'Cita reprogramada', @ID_USUARIO
        FROM dbo.TB_CITA WHERE ID_CITA = @ID_CITA;

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

IF OBJECT_ID('dbo.usp_Cita_Cancelar', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Cita_Cancelar;
GO

CREATE PROCEDURE dbo.usp_Cita_Cancelar
    @ID_CITA        INT,
    @ID_USUARIO     INT,
    @MOTIVO         VARCHAR(300) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    BEGIN TRY
        BEGIN TRANSACTION;

        DECLARE @ID_DISPONIBILIDAD INT, @ESTADO_ANTERIOR VARCHAR(15);

        SELECT @ID_DISPONIBILIDAD = C.ID_DISPONIBILIDAD,
               @ESTADO_ANTERIOR = C.ESTADO
        FROM dbo.TB_CITA C
        INNER JOIN dbo.TM_MASCOTA M ON M.ID_MASCOTA = C.ID_MASCOTA
        WHERE C.ID_CITA = @ID_CITA
          AND M.ID_USUARIO = @ID_USUARIO
          AND C.ESTADO IN ('PENDIENTE','CONFIRMADA');

        IF @ID_DISPONIBILIDAD IS NULL
            THROW 50010, 'La cita no existe o no puede cancelarse.', 1;

        UPDATE dbo.TB_CITA
           SET ESTADO = 'CANCELADA',
               FECHA_MODIFICACION = SYSDATETIME()
         WHERE ID_CITA = @ID_CITA;

        UPDATE dbo.TB_DISPONIBILIDAD
           SET ESTADO = 'DISPONIBLE'
         WHERE ID_DISPONIBILIDAD = @ID_DISPONIBILIDAD;

        INSERT INTO dbo.TB_CITA_ESTADO_HISTORIAL
            (ID_CITA, ESTADO_ANTERIOR, ESTADO_NUEVO, MOTIVO, ID_USUARIO_ACCION)
        VALUES
            (@ID_CITA, @ESTADO_ANTERIOR, 'CANCELADA', @MOTIVO, @ID_USUARIO);

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

IF OBJECT_ID('dbo.usp_Pago_Registrar', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Pago_Registrar;
GO

CREATE PROCEDURE dbo.usp_Pago_Registrar
    @ID_CITA              INT,
    @METODO               VARCHAR(20),
    @ESTADO               VARCHAR(15),
    @CODIGO_TRANSACCION   VARCHAR(80) = NULL,
    @ULTIMOS_4            CHAR(4) = NULL,
    @ID_PAGO              INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    BEGIN TRY
        BEGIN TRANSACTION;

        DECLARE @MONTO DECIMAL(10,2), @ESTADO_CITA VARCHAR(15);

        SELECT @MONTO = PRECIO_RESERVADO, @ESTADO_CITA = ESTADO
        FROM dbo.TB_CITA WITH (UPDLOCK, HOLDLOCK)
        WHERE ID_CITA = @ID_CITA;

        IF @MONTO IS NULL
            THROW 50011, 'La cita indicada no existe.', 1;

        IF @ESTADO_CITA = 'CANCELADA'
            THROW 50012, 'No se puede pagar una cita cancelada.', 1;

        INSERT INTO dbo.TB_PAGO
            (ID_CITA, MONTO, METODO, ESTADO, CODIGO_TRANSACCION,
             ULTIMOS_4, FECHA_PAGO)
        VALUES
            (@ID_CITA, @MONTO, @METODO, @ESTADO, @CODIGO_TRANSACCION,
             @ULTIMOS_4, CASE WHEN @ESTADO = 'APROBADO' THEN SYSDATETIME() ELSE NULL END);

        SET @ID_PAGO = CONVERT(INT, SCOPE_IDENTITY());

        IF @ESTADO = 'APROBADO' AND @ESTADO_CITA = 'PENDIENTE'
        BEGIN
            UPDATE dbo.TB_CITA
               SET ESTADO = 'CONFIRMADA',
                   FECHA_MODIFICACION = SYSDATETIME()
             WHERE ID_CITA = @ID_CITA;

            INSERT INTO dbo.TB_CITA_ESTADO_HISTORIAL
                (ID_CITA, ESTADO_ANTERIOR, ESTADO_NUEVO, MOTIVO)
            VALUES
                (@ID_CITA, 'PENDIENTE', 'CONFIRMADA', 'Pago aprobado');
        END;

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

/*==============================================================
  PROCEDIMIENTOS COMPLEMENTARIOS DEL FRONTEND
==============================================================*/
IF OBJECT_ID('dbo.usp_Usuario_Actualizar', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Usuario_Actualizar;
GO

CREATE PROCEDURE dbo.usp_Usuario_Actualizar
 @ID_USUARIO INT,@NOMBRES VARCHAR(80),@APELLIDOS VARCHAR(100),@CORREO VARCHAR(120),
 @TELEFONO VARCHAR(20)=NULL,@TIPO_DOCUMENTO VARCHAR(10)=NULL,@NUMERO_DOCUMENTO VARCHAR(15)=NULL,@DIRECCION VARCHAR(200)=NULL
AS
BEGIN
 SET NOCOUNT ON;
 IF EXISTS(SELECT 1 FROM dbo.TM_USUARIO WHERE CORREO=LOWER(LTRIM(RTRIM(@CORREO))) AND ID_USUARIO<>@ID_USUARIO) THROW 50100,'El correo ya pertenece a otro usuario.',1;
 UPDATE dbo.TM_USUARIO SET NOMBRES=@NOMBRES,APELLIDOS=@APELLIDOS,CORREO=LOWER(LTRIM(RTRIM(@CORREO))),TELEFONO=@TELEFONO,TIPO_DOCUMENTO=@TIPO_DOCUMENTO,NUMERO_DOCUMENTO=@NUMERO_DOCUMENTO,DIRECCION=@DIRECCION,FECHA_MODIFICACION=SYSDATETIME() WHERE ID_USUARIO=@ID_USUARIO AND ACTIVO=1;
 IF @@ROWCOUNT=0 THROW 50101,'Usuario no encontrado.',1;
END;
GO
IF OBJECT_ID('dbo.usp_Dashboard_Obtener', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Dashboard_Obtener;
GO

CREATE PROCEDURE dbo.usp_Dashboard_Obtener @ID_USUARIO INT AS
BEGIN
 SET NOCOUNT ON;
 SELECT (SELECT COUNT(*) FROM dbo.TM_MASCOTA WHERE ID_USUARIO=@ID_USUARIO AND ACTIVO=1) TOTAL_MASCOTAS,
 (SELECT COUNT(*) FROM dbo.TB_CITA C JOIN dbo.TM_MASCOTA M ON M.ID_MASCOTA=C.ID_MASCOTA JOIN dbo.TB_DISPONIBILIDAD D ON D.ID_DISPONIBILIDAD=C.ID_DISPONIBILIDAD WHERE M.ID_USUARIO=@ID_USUARIO AND C.ESTADO IN('PENDIENTE','CONFIRMADA') AND D.FECHA_ATENCION>=CAST(GETDATE() AS DATE)) CITAS_PROXIMAS,
 (SELECT COUNT(*) FROM dbo.TB_CITA C JOIN dbo.TM_MASCOTA M ON M.ID_MASCOTA=C.ID_MASCOTA WHERE M.ID_USUARIO=@ID_USUARIO AND C.ESTADO='COMPLETADA') CITAS_COMPLETADAS;
 SELECT TOP 3 C.ID_CITA,M.NOMBRE,S.NOMBRE,D.FECHA_ATENCION,D.HORA_INICIO,C.ESTADO FROM dbo.TB_CITA C JOIN dbo.TM_MASCOTA M ON M.ID_MASCOTA=C.ID_MASCOTA JOIN dbo.TM_SERVICIO S ON S.ID_SERVICIO=C.ID_SERVICIO JOIN dbo.TB_DISPONIBILIDAD D ON D.ID_DISPONIBILIDAD=C.ID_DISPONIBILIDAD WHERE M.ID_USUARIO=@ID_USUARIO AND C.ESTADO IN('PENDIENTE','CONFIRMADA') ORDER BY D.FECHA_ATENCION,D.HORA_INICIO;
END;
GO
IF OBJECT_ID('dbo.usp_Catalogos_Listar', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Catalogos_Listar;
GO

CREATE PROCEDURE dbo.usp_Catalogos_Listar AS
BEGIN SET NOCOUNT ON;
 SELECT ID_ESPECIE,NOMBRE FROM dbo.TM_ESPECIE WHERE ACTIVO=1 ORDER BY NOMBRE;
 SELECT ID_SERVICIO,NOMBRE,DESCRIPCION,DURACION_MINUTOS,PRECIO FROM dbo.TM_SERVICIO WHERE ACTIVO=1 ORDER BY NOMBRE;
 SELECT ID_VETERINARIO,CONCAT(NOMBRES,' ',APELLIDOS),ESPECIALIDAD FROM dbo.TM_VETERINARIO WHERE ACTIVO=1 ORDER BY NOMBRES;
END;
GO
IF OBJECT_ID('dbo.usp_Mascota_Obtener', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Mascota_Obtener;
GO

CREATE PROCEDURE dbo.usp_Mascota_Obtener @ID_MASCOTA INT,@ID_USUARIO INT AS
BEGIN SET NOCOUNT ON;
 SELECT M.ID_MASCOTA,M.ID_USUARIO,M.ID_ESPECIE,M.NOMBRE,E.NOMBRE,M.RAZA,M.SEXO,M.FECHA_NACIMIENTO,M.PESO_KG,M.COLOR,M.ESTERILIZADO,M.MICROCHIP,M.FOTO_URL,M.OBSERVACIONES FROM dbo.TM_MASCOTA M JOIN dbo.TM_ESPECIE E ON E.ID_ESPECIE=M.ID_ESPECIE WHERE M.ID_MASCOTA=@ID_MASCOTA AND M.ID_USUARIO=@ID_USUARIO AND M.ACTIVO=1;
 SELECT VA.ID_VACUNA,VA.NOMBRE_VACUNA,VA.FECHA_APLICACION,VA.FECHA_PROXIMA,CONCAT(V.NOMBRES,' ',V.APELLIDOS),VA.OBSERVACIONES FROM dbo.TB_VACUNA_MASCOTA VA LEFT JOIN dbo.TM_VETERINARIO V ON V.ID_VETERINARIO=VA.ID_VETERINARIO WHERE VA.ID_MASCOTA=@ID_MASCOTA ORDER BY VA.FECHA_APLICACION DESC;
 SELECT CO.ID_CONSULTA,CO.FECHA_CONSULTA,CO.DIAGNOSTICO,CO.TRATAMIENTO,CO.PESO_KG,CONCAT(V.NOMBRES,' ',V.APELLIDOS) FROM dbo.TB_CONSULTA_MASCOTA CO LEFT JOIN dbo.TM_VETERINARIO V ON V.ID_VETERINARIO=CO.ID_VETERINARIO WHERE CO.ID_MASCOTA=@ID_MASCOTA ORDER BY CO.FECHA_CONSULTA DESC;
 SELECT ID_DOCUMENTO,NOMBRE,TIPO,URL,FECHA_CREACION FROM dbo.TB_DOCUMENTO_MASCOTA WHERE ID_MASCOTA=@ID_MASCOTA ORDER BY FECHA_CREACION DESC;
END;
GO
IF OBJECT_ID('dbo.usp_Cita_Obtener', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Cita_Obtener;
GO

CREATE PROCEDURE dbo.usp_Cita_Obtener @ID_CITA INT,@ID_USUARIO INT AS
BEGIN SET NOCOUNT ON;
 SELECT C.ID_CITA,M.ID_MASCOTA,M.NOMBRE,E.NOMBRE,M.RAZA,S.ID_SERVICIO,S.NOMBRE,C.PRECIO_RESERVADO,D.ID_DISPONIBILIDAD,D.FECHA_ATENCION,D.HORA_INICIO,D.HORA_FIN,V.ID_VETERINARIO,CONCAT(V.NOMBRES,' ',V.APELLIDOS),V.ESPECIALIDAD,C.ESTADO,C.MOTIVO_CONSULTA,C.OBSERVACIONES FROM dbo.TB_CITA C JOIN dbo.TM_MASCOTA M ON M.ID_MASCOTA=C.ID_MASCOTA JOIN dbo.TM_ESPECIE E ON E.ID_ESPECIE=M.ID_ESPECIE JOIN dbo.TM_SERVICIO S ON S.ID_SERVICIO=C.ID_SERVICIO JOIN dbo.TB_DISPONIBILIDAD D ON D.ID_DISPONIBILIDAD=C.ID_DISPONIBILIDAD JOIN dbo.TM_VETERINARIO V ON V.ID_VETERINARIO=C.ID_VETERINARIO WHERE C.ID_CITA=@ID_CITA AND M.ID_USUARIO=@ID_USUARIO;
 SELECT ID_PAGO,MONTO,METODO,ESTADO,CODIGO_TRANSACCION,ULTIMOS_4,FECHA_PAGO FROM dbo.TB_PAGO WHERE ID_CITA=@ID_CITA ORDER BY ID_PAGO DESC;
END;
GO
IF OBJECT_ID('dbo.usp_Vacuna_Registrar', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Vacuna_Registrar;
GO

CREATE PROCEDURE dbo.usp_Vacuna_Registrar @ID_MASCOTA INT,@NOMBRE_VACUNA VARCHAR(120),@FECHA_APLICACION DATE,@FECHA_PROXIMA DATE=NULL,@ID_VETERINARIO INT=NULL,@OBSERVACIONES VARCHAR(300)=NULL,@ID_VACUNA INT OUTPUT AS BEGIN SET NOCOUNT ON; INSERT dbo.TB_VACUNA_MASCOTA(ID_MASCOTA,ID_VETERINARIO,NOMBRE_VACUNA,FECHA_APLICACION,FECHA_PROXIMA,OBSERVACIONES) VALUES(@ID_MASCOTA,@ID_VETERINARIO,@NOMBRE_VACUNA,@FECHA_APLICACION,@FECHA_PROXIMA,@OBSERVACIONES); SET @ID_VACUNA=SCOPE_IDENTITY(); END;
GO
IF OBJECT_ID('dbo.usp_Consulta_Registrar', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Consulta_Registrar;
GO

CREATE PROCEDURE dbo.usp_Consulta_Registrar @ID_MASCOTA INT,@ID_VETERINARIO INT=NULL,@FECHA_CONSULTA DATETIME2,@DIAGNOSTICO VARCHAR(500),@TRATAMIENTO VARCHAR(500)=NULL,@PESO_KG DECIMAL(6,2)=NULL,@ID_CONSULTA INT OUTPUT AS BEGIN SET NOCOUNT ON; INSERT dbo.TB_CONSULTA_MASCOTA(ID_MASCOTA,ID_VETERINARIO,FECHA_CONSULTA,DIAGNOSTICO,TRATAMIENTO,PESO_KG) VALUES(@ID_MASCOTA,@ID_VETERINARIO,@FECHA_CONSULTA,@DIAGNOSTICO,@TRATAMIENTO,@PESO_KG); SET @ID_CONSULTA=SCOPE_IDENTITY(); END;
GO
IF OBJECT_ID('dbo.usp_Documento_Registrar', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Documento_Registrar;
GO

CREATE PROCEDURE dbo.usp_Documento_Registrar @ID_MASCOTA INT,@NOMBRE VARCHAR(150),@TIPO VARCHAR(50),@URL VARCHAR(500),@DESCRIPCION VARCHAR(300)=NULL,@ID_DOCUMENTO INT OUTPUT AS BEGIN SET NOCOUNT ON; INSERT dbo.TB_DOCUMENTO_MASCOTA(ID_MASCOTA,NOMBRE,TIPO,URL,DESCRIPCION) VALUES(@ID_MASCOTA,@NOMBRE,@TIPO,@URL,@DESCRIPCION); SET @ID_DOCUMENTO=SCOPE_IDENTITY(); END;
GO


/*==============================================================
  PROCEDIMIENTO: CAMBIAR CONTRASEÑA DEL USUARIO
==============================================================*/
IF OBJECT_ID('dbo.usp_Usuario_CambiarClave', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_Usuario_CambiarClave;
GO

CREATE PROCEDURE dbo.usp_Usuario_CambiarClave
    @ID_USUARIO INT,
    @CLAVE_NUEVA VARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    IF @ID_USUARIO IS NULL OR @ID_USUARIO <= 0
        THROW 50109, 'El identificador del usuario no es válido.', 1;

    IF NULLIF(LTRIM(RTRIM(@CLAVE_NUEVA)), '') IS NULL
        THROW 50110, 'La nueva contraseña es obligatoria.', 1;

    IF NOT EXISTS
    (
        SELECT 1
        FROM dbo.TM_USUARIO
        WHERE ID_USUARIO = @ID_USUARIO
          AND ACTIVO = 1
    )
        THROW 50111, 'Usuario no encontrado o inactivo.', 1;

    UPDATE dbo.TM_USUARIO
       SET CLAVE = @CLAVE_NUEVA,
           FECHA_MODIFICACION = SYSDATETIME()
     WHERE ID_USUARIO = @ID_USUARIO
       AND ACTIVO = 1;
END;
GO

/*==============================================================
  VERIFICACIÓN FINAL DE PROCEDIMIENTOS
==============================================================*/
DECLARE @ProcedimientosEsperados TABLE (NOMBRE SYSNAME);

INSERT INTO @ProcedimientosEsperados (NOMBRE)
VALUES
('usp_Usuario_Registrar'),
('usp_Usuario_Login'),
('usp_Usuario_ObtenerPerfil'),
('usp_Mascota_ListarPorUsuario'),
('usp_Mascota_Registrar'),
('usp_Mascota_Actualizar'),
('usp_Mascota_Eliminar'),
('usp_Servicio_Listar'),
('usp_Disponibilidad_Listar'),
('usp_Cita_ListarPorUsuario'),
('usp_Cita_Registrar'),
('usp_Cita_Reprogramar'),
('usp_Cita_Cancelar'),
('usp_Pago_Registrar'),
('usp_Usuario_Actualizar'),
('usp_Dashboard_Obtener'),
('usp_Catalogos_Listar'),
('usp_Mascota_Obtener'),
('usp_Cita_Obtener'),
('usp_Vacuna_Registrar'),
('usp_Consulta_Registrar'),
('usp_Documento_Registrar'),
('usp_Usuario_CambiarClave');

IF EXISTS
(
    SELECT 1
    FROM @ProcedimientosEsperados E
    WHERE OBJECT_ID('dbo.' + E.NOMBRE, 'P') IS NULL
)
BEGIN
    SELECT E.NOMBRE AS PROCEDIMIENTO_FALTANTE
    FROM @ProcedimientosEsperados E
    WHERE OBJECT_ID('dbo.' + E.NOMBRE, 'P') IS NULL;

    THROW 51001, 'No se crearon todos los procedimientos almacenados.', 1;
END;

SELECT
    S.name AS ESQUEMA,
    P.name AS PROCEDIMIENTO,
    P.create_date AS FECHA_CREACION,
    P.modify_date AS FECHA_MODIFICACION
FROM sys.procedures P
INNER JOIN sys.schemas S ON S.schema_id = P.schema_id
WHERE S.name = 'dbo'
  AND P.name IN (SELECT NOMBRE FROM @ProcedimientosEsperados)
ORDER BY P.name;
GO
